services:
  db:
    image: mysql:8.0.44-debian
    container_name: mysql_real_state
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: myfirstpassword
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      TZ: America/Sao_Paulo
      PHP_INI_DATE_TIMEZONE: America/Sao_Paulo
      
    ports:
      - "3306:3306"
      
    volumes:
      - db_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
      - ./php-ext-config/mysqli.ini:/usr/local/etc/php/conf.d/mysqli.ini
      
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_app
    restart: always
    environment:
      TZ: America/Sao_Paulo
    working_dir: /var/www/html
    volumes:
      - ..:/var/www/html
      
  web:
    image: nginx:stable-alpine
    container_name: nginx_web
    restart: always
    ports:
      - "80:80"
    volumes:
      - ..:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db

volumes:
  db_data: